namespace Crestacle.Bedrock.Core.Enumerations;

/// <summary>Identifies the security event recorded in an audit log entry.</summary>
public enum AuditEventType
{
    LoginSucceeded,
    LoginFailed,
    AccountLocked,
    AccountUnlocked,
    EmailVerified,
    PasswordChanged,
    PasswordReset,
    PasswordResetRequested,
    MfaEnabled,
    MfaDisabled,
    MfaChallengeSucceeded,
    MfaChallengeFailed,
    RecoveryCodeUsed,
    RecoveryCodesRegenerated,
    StepUpCompleted,
    StepUpFailed,
    TokenRefreshed,
    TokenRevoked,
    SessionRevoked,
    AnomalyDetected,
    AccountAnonymized,
    EmailChangeRequested,
    EmailChanged,
    MagicLinkRequested,
    MagicLinkConsumed,
    PasskeyRegistered,
    PasskeyAuthenticated,
    PasskeyDeleted,
    ExternalLoginSucceeded,
    ExternalIdentityLinked,
    ExternalIdentityUnlinked,
    AdminAccountLocked,
    AdminAccountUnlocked,
    AdminMfaReset,
    AdminPasswordExpired,
    AdminSessionsRevoked,
    InvitationCreated,
    InvitationAccepted,
    ApiKeyCreated,
    ApiKeyRevoked
}
